<a href="https://colab.research.google.com/github/Vignesh424/Pokemon-Regression/blob/main/RandomForestPokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [230]:
#import libraries
import numpy as np
import pandas as pd

In [231]:
data=pd.read_csv('/content/pokedex_(Update_05.20).csv')

In [232]:
data.head()

   Unnamed: 0  pokedex_number  ... against_steel against_fairy
0           0               1  ...           1.0           0.5
1           1               2  ...           1.0           0.5
2           2               3  ...           1.0           0.5
3           3               3  ...           1.0           0.5
4           4               4  ...           0.5           0.5

[5 rows x 51 columns]

In [233]:
data.isnull().sum()
data.isnull().any()

Unnamed: 0          False
pokedex_number      False
name                False
german_name          True
japanese_name        True
generation          False
status              False
species             False
type_number         False
type_1              False
type_2               True
height_m            False
weight_kg            True
abilities_number    False
ability_1            True
ability_2            True
ability_hidden       True
total_points        False
hp                  False
attack              False
defense             False
sp_attack           False
sp_defense          False
speed               False
catch_rate           True
base_friendship      True
base_experience      True
growth_rate          True
egg_type_number     False
egg_type_1           True
egg_type_2           True
percentage_male      True
egg_cycles           True
against_normal      False
against_fire        False
against_water       False
against_electric    False
against_grass       False
against_ice         False
against_fight       False
against_poison      False
against_ground      False
against_flying      False
against_psychic     False
against_bug         False
against_rock        False
against_ghost       False
against_dragon      False
against_dark        False
against_steel       False
against_fairy       False
dtype: bool

In [234]:
data.index

RangeIndex(start=0, stop=1028, step=1)

In [235]:
data = data.fillna(method='ffill')

In [236]:
x1=data.drop("Unnamed: 0" ,axis=1)

In [237]:
x1.head()

   pokedex_number           name  ... against_steel against_fairy
0               1      Bulbasaur  ...           1.0           0.5
1               2        Ivysaur  ...           1.0           0.5
2               3       Venusaur  ...           1.0           0.5
3               3  Mega Venusaur  ...           1.0           0.5
4               4     Charmander  ...           0.5           0.5

[5 rows x 50 columns]

In [238]:
x=x1.drop(columns=['pokedex_number', 'german_name', 'abilities_number','height_m', 'weight_kg', 
                   'growth_rate','japanese_name', 'base_friendship', 'catch_rate','egg_type_number', 'ability_1',
                   'ability_2',  'ability_hidden','egg_type_1', 'egg_type_2', 'percentage_male','egg_cycles' ,
                   'against_normal', 'against_fire', 'against_water', 'against_electric', 'against_grass',
                   'against_ice', 'against_fight', 'against_poison', 'against_ground', 'against_flying',
                   'against_psychic', 'against_bug', 'against_rock', 'against_ghost', 'against_dragon',
                   'against_dark', 'against_steel', 'against_fairy'])
x.head()

            name  generation  status  ... sp_defense  speed base_experience
0      Bulbasaur           1  Normal  ...         65     45            64.0
1        Ivysaur           1  Normal  ...         80     60           142.0
2       Venusaur           1  Normal  ...        100     80           236.0
3  Mega Venusaur           1  Normal  ...        120     80           281.0
4     Charmander           1  Normal  ...         50     65            62.0

[5 rows x 15 columns]

In [239]:
# Preparing the data 
X = x.iloc[:,7:-1].values
y = x.iloc[:,4].values

In [240]:
X

array([[ 318,   45,   49, ...,   65,   65,   45],
       [ 405,   60,   62, ...,   80,   80,   60],
       [ 525,   80,   82, ...,  100,  100,   80],
       ...,
       [ 670,   92,  130, ...,   80,  115,  138],
       [ 690,  140,   85, ...,  145,   95,  130],
       [1125,  255,  115, ...,  125,  250,  130]])

In [241]:
y

array([2, 2, 2, ..., 1, 2, 2])

In [242]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.30)

In [243]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators =100)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [244]:
y_pred = classifier.predict(X_test)

In [245]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[ 74  64]
 [ 64 107]]

In [246]:
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

Classification Report:
              precision    recall  f1-score   support

           1       0.54      0.54      0.54       138
           2       0.63      0.63      0.63       171

    accuracy                           0.59       309
   macro avg       0.58      0.58      0.58       309
weighted avg       0.59      0.59      0.59       309

In [247]:
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Accuracy: 0.5857605177993528